name: Deploy master branch

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/checkout@v2
        with:
          path: "public"
          ref: gh-pages

      - name: recon
        run: ls -l *

      - name: install hugo
        run: sudo apt-get -q install hugo

      - name: build the site
        run: hugo version && hugo

      - name: commit changes to gh-pages branch
        # perhaps reuse the commit message from the original commit
        run: |
          cd public
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add --all && git commit -m "Update blog" && git push
